### ISSUE TITLE
Automatically apply Smash materials (enhancement)

### ISSUE THREAD

**Issue by imod-commission** [ssbucarlos/smash-ultimate-blender#124]
When exporting a model from blender, the materials could be converted to basic Smash material (Mario PRM) and keep the name. After that we can do edit outside blender such as apply presets with SSBH Editor/Crossmod

**Comment by ScanMountGoat** [comment]
Materials with no Smash Ultimate node group are automatically converted to a default material similar to the Mario PRM preset on export. The material label is the name of the material in Blender. The base color texture is used to infer the col map name. Inferring the nor map name will be added in a later update. See issue #101.
