### ISSUE TITLE
Python Error While Exporting

### ISSUE THREAD

**Issue by felixbento22** [ssbucarlos/smash-ultimate-blender#126]
Whenever Exporting, this error throws. 

`Python:` Traceback (most recent call last):
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\smash-ultimate-blender-main\panels\export_model.py", line 134, in execute
    export_model(self, context, self.filepath, self.include_numdlb, self.include_numshb, self.include_numshexb,
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\smash-ultimate-blender-main\panels\export_model.py", line 189, in export_model
    ssbh_modl_data.save(str(folder.joinpath('model.numdlb')))
FileNotFoundError: The system cannot find the path specified. (os error 3)

location: <unknown location>:-1'

Apologize if I am just missing something obvious
File for reference

[yosuke try3.zip](https://github.com/ssbucarlos/smash-ultimate-blender/files/9155637/yosuke.try3.zip)

**Comment by ScanMountGoat** [comment]
This error shouldn't happen normally. Does the folder exist where you're trying to save the file?

**Comment by felixbento22** [comment]
> 

yeah it happens on any folder i try to save to

**Comment by ScanMountGoat** [comment]
I'm not getting that error when I try and save.

**Comment by felixbento22** [comment]
Hmm, ill try reinstalling blender

**Comment by ScanMountGoat** [comment]
Check if you can save other files from Blender to that folder. This likely isn't something we can fix on our end.
