### ISSUE TITLE
Incorrect Mesh Visualization

### ISSUE THREAD

**Issue by S1roos** [ssbucarlos/smash-ultimate-blender#127]
![image](https://user-images.githubusercontent.com/93221553/180123329-40b6b676-4860-480f-8dc3-6bab3414864d.png)
![2022072022220200-0E7DF678130F4F0FA2C88AE72B47AFDF](https://user-images.githubusercontent.com/93221553/180123389-f026f273-d594-4ad2-bbe3-ffdcb87a9abf.jpg)
![image](https://user-images.githubusercontent.com/93221553/180123655-5d33fffc-a2f3-4188-84a4-a2e06d6acc20.png)

As you can see here, the mesh in SSBH seems to display as if its weights are not limited to 4 (top image). The visualiztion is fixed in SSBH if the mesh names are not identical (here I appended .A and .B to the ends, bottom image). However, the mesh is displayed correctly ingame (middle image), even without changing the mesh names. I've attatched the blend used to create the mod as well.

[Link to google drive with blend](https://drive.google.com/file/d/1WfHECj8NDnNgYBguV5lmOmVOzBd2Z88W/view?usp=sharing)

**Comment by ScanMountGoat** [comment]
The mesh is exporting out of blender with the same sub index assigned to two different meshes of the same name. This should never happen, so I'm not too worried about SSBH Editor not matching in game. This is relatively straightforward to fix for Smash Ultimate Blender.

**Comment by ScanMountGoat** [comment]
This should be fixed on the latest commit.
