### ISSUE TITLE
Enabling Error MacOS

### ISSUE THREAD

**Issue by progenitor7** [ssbucarlos/smash-ultimate-blender#129]
Greetings!

There is an error when attempting to enable the plugin on Mac. I saw that there was a similar issue with a Linux user in Issue #30. The error I get is a little different however.

<img width="847" alt="Screen Shot 2022-08-05 at 1 38 17 AM" src="https://user-images.githubusercontent.com/109327944/183009214-ad2b4d6a-9551-4bdd-906c-86a7088de4dd.png">

I'll add that I've deleted data relating to builds 2.8 and 3.2 which are what I have used in the past in favor of using 3.0 but the issue persists.

**Comment by ScanMountGoat** [comment]
I've removed those lines of code, so this specific issue is fixed on the latest commit. Thanks for the heads up.

In order for the addon to work properly on MacOS and Linux, I need to make importing not fail if the model.nuhlp fails to import. The current implementation uses a Windows only program to read the nuhlpb file. This should be an easy fix for now as long as you disable nuhlpb export in the export menu.

All the nuhlpb functionality like import, export, and exo skel will work properly on Linux and MacOS in a future update, but the changes aren't quite ready yet. The plan is for this to coincide with supporting only Blender 3.1 or newer, which is another reason to wait a little longer.

**Comment by ScanMountGoat** [comment]
@progenitor7 this is working for me now on the latest commit on my MacBook. If you encounter any issues other than nuhlpb functionality not working, feel free to make a separate issue.

**Comment by progenitor7** [comment]
It's working for me now. Thanks!
