### ISSUE TITLE
UVs outside 0.0 to 1.0 range not working as expected on export (WrapMode)

### ISSUE THREAD

**Issue by CattailXC** [ssbucarlos/smash-ultimate-blender#135]
I talked about this in the SUM Discord server with SMG, with my initial post being found here: https://discord.com/channels/447823426061860879/516433603031334915/1013631399900762152
and our conversation being here: https://discord.com/channels/447823426061860879/516433603031334915/1013832563606949898
I'm not sure how I can better explain this issue without repeating that conversation so all of the context is in there. This google drive link has both the Blend shown as well as a ZIP containing the mod files I'm using for this mod: https://drive.google.com/drive/folders/1c_Psv2obORMMzr48hc_nuNiUPa9DCjx3?usp=sharing 
I've tried manually splitting the UVs before export with no luck. Thank you for your time and I hope you can find the source of this issue.

**Comment by ScanMountGoat** [comment]
![image](https://user-images.githubusercontent.com/23301691/187251290-65c7698b-c82e-446e-9072-708ec41fd781.png)
@CattailXC set the WrapS and WrapT to Repeat in SSBH Editor in the material editor under advanced settings. I'll look into making this the default in Blender and when applying presets in SSBH Editor to reduce the chances of this happening in the future. This could also be something that I can add as a validation check to SSBH Editor.

**Comment by CattailXC** [comment]
I completely missed those UVs, apologies for that.
![image](https://user-images.githubusercontent.com/97373686/187253564-0cc0666d-fa3f-47af-ac66-f6d175594860.png)
Setting the WrapS and WrapT to Repeat reduces how noticeable it is, but there's still a faint outline. Not sure if this will even be noticeable in-game though. Thanks a lot!

**Comment by ScanMountGoat** [comment]
You can try moving those UVs to be connected to the rest of the face. You may have some tangent related seams due to how the UVs are positioned currently.

**Comment by ScanMountGoat** [comment]
Closing since SSBH Editor now checks for this
