### ISSUE TITLE
Remove top armature node / MaxScript exported model compatibility?

### ISSUE THREAD

**Issue by TabuuForteAkugun** [ssbucarlos/smash-ultimate-blender#140]
Hey Carlos and SMG!

First of all congrats on the new update for the plugin! It's been a long time coming and I bet it feels cool!!

But I have questions, more than issues, I'd say.

1. Is it possible to export, ie, Mario's model without the top node called "smush_armature_import?". It messes up the keyframes in the animations because it looks for, ie, "smush_armature_import/Trans rather than just Trans. I export both to FBX, btw, if ya need to know. I wanted to export the mesh and bones alone and not the container. Is that with the plugin or is it a Blender issue?
2. Next up, I use the MaxScript .NUMDLB importer by Random Talking Bush to import/convert the models. (and export to FBX via Max). I've made no changes whatsoever to the vanilla bonesets, I just wanted to test the animation importer for compatibility with my Unity setup. I don't mind manually doing the conversions (numdlb/nuanmb -> fbx). And when I export the model via Blender, it's huge: the smush_armature_import object scales it by 100, and it won't let me remove that new "root".

Thanks, and sorry if I'm bugging~!

**Comment by ScanMountGoat** [comment]
> 1. Is it possible to export, ie, Mario's model without the top node called "smush_armature_import?". It messes up the keyframes in the animations because it looks for, ie, "smush_armature_import/Trans rather than just Trans. I export both to FBX, btw, if ya need to know. I wanted to export the mesh and bones alone and not the container. Is that with the plugin or is it a Blender issue?

We don't really do anything different compared to a normal Blender scene in terms of the scene setup. You can always rename the armature if it's causing issues. There should be guides on exporting from Blender to Unity.

> 2. Next up, I use the MaxScript .NUMDLB importer by Random Talking Bush to import/convert the models. (and export to FBX via Max). I've made no changes whatsoever to the vanilla bonesets, I just wanted to test the animation importer for compatibility with my Unity setup. I don't mind manually doing the conversions (numdlb/nuanmb -> fbx). And when I export the model via Blender, it's huge: the smush_armature_import object scales it by 100, and it won't let me remove that new "root".

We don't apply any scaling to the model on import or export in Blender. I would look into unit conversions settings in Blender. The applications might not be using the same units. Importing animations on models imported from other applications may or may not work as expected depending on how the armature is set up. The addon applies helper bone constraints from the model.nuhlpb file, which won't be present when importing from FBX.

**Comment by TabuuForteAkugun** [comment]
Thanks for clearing it up. I just wondered because of my game having NEW characters and their being set up in max, etc.

I love this tool, it's a great achievement but it may not solve my particular needs for this project (this isn't a mod).

Thanks SMG! It's definitely a Max VS Blender issue.
