### ISSUE TITLE
Improve mesh transparency preview in blender.

### ISSUE THREAD

**Issue by ssbucarlos** [ssbucarlos/smash-ultimate-blender#141]
1.) Use BlendState rather than shader label
![image](https://user-images.githubusercontent.com/77519735/191883828-16a5ede0-72ef-48f4-b03b-38fe4dd2296d.png)
2.) Investigate these nodes, since the alpha is being incorrectly clamped to a min of .5
![image](https://user-images.githubusercontent.com/77519735/191884002-8244c69f-9086-44d7-a0cf-cd1d02e5f7a3.png)

**Comment by ssbucarlos** [comment]
For testing of colorSet1 alpha, need to find a model whose mesh has colorSet1 with non-default (0.5) values set and see the expected mixing behavior between the alpha from colorSet1 and texture0

**Comment by ssbucarlos** [comment]
@ScanMountGoat How did u determine the 'discard' for alpha testing of the material? I checked ssbh_editor and i noticed its available in the 'SHADER_JSON' file, but the `Nufx.db` included in smush_blender doesn't have it since the `nuc2effectlibrary.nufxlb.json` file doesn't have it either.

**Comment by ScanMountGoat** [comment]
SSBH Editor is using an updated shader info JSON file generated from a Rust program on the smush_material_research repo. This includes additional data found by analyzing the decompiled shaders and nushdb files.
https://github.com/ScanMountGoat/Smush-Material-Research#shader-info

The old code using Python and JSON was pretty slow. We can probably speed it up a lot by loading the JSON file once when the addon is loaded in a global variable. I'm not sure how much of the added data in the new JSON is critical for Blender.

**Comment by ssbucarlos** [comment]
all i can think of possibly using for now is the discard info. I would like to continue using the sqlite db tho, i will look into this further

**Comment by ssbucarlos** [comment]
since all i need for now is just the 'discard' for each shader label, from that json file i made a dict and wrote it to a text file for loading into smush blender, not sure how fast that is gonna be. dict looks like this `{'SFX_PBS_0000000000000080': False, 'SFX_PBS_0000000000000084': False, ...}`

**Comment by ScanMountGoat** [comment]
There should be a list of shaders with discard (alpha testing) on the material research repo. You don't need to store all the shaders if it's just a boolean flag. This would be implemented as a set in Python for fast lookups.

**Comment by ssbucarlos** [comment]
ur so right that would be alot better

**Comment by ssbucarlos** [comment]
https://docs.blender.org/manual/en/dev/render/eevee/materials/settings.html#sorting-problem
>As of now Eevee does not support per-fragment (pixel) sorting or per-triangle sorting. Only per-object sorting is available and is automatically done on all transparent surfaces based on object origin.
Per-fragment or per-triangle sorting is how ssbh_editor is able to handle mesh self-sorting issues right?
I may be using the wrong terminology so heres an example.
![image](https://user-images.githubusercontent.com/77519735/192073977-496af855-5e3b-43b5-8612-a8ce42616739.png)
Despite having no other meshes around this mesh seems to have sorting issues when using alpha blend, which from documentation i believed should have been the correct approximation of blend state `OneMinusSourceAlpha`
If the issue is a limitation with eevee, as a workaround imported meshes can be assigned alpha hashing behavior

**Comment by ScanMountGoat** [comment]
Polygon sorting is too expensive to do in game in real time. It shouldn't be necessary for the meshes to render properly.

**Comment by ssbucarlos** [comment]
I probably need to do more research in blender to get 'alpha blend' to work like i expected, or maybe i just misunderstood the needed blending behavior. In the meantime, im pushing a small improvement.

**Comment by ssbucarlos** [comment]
reopened because i did not mean to close woops

**Comment by ssbucarlos** [comment]
atm im not sure theres anything i can do about this
