### ISSUE TITLE
cross platform support

### ISSUE THREAD

**Issue by ScanMountGoat** [ssbucarlos/smash-ultimate-blender#147]
This should be included with the update to Blender 3.1+
- [x] use ssbh_data_py for hlpb instead of ssbh_lib_json
- [x] add arm64 binaries for macos for pyprc

**Comment by ssbucarlos** [comment]
I'll take care of moving to ssbh_data_py instead of ssbh_lib_json, just lmk whenever it is possible to do so.

**Comment by ScanMountGoat** [comment]
Ok great. I just need to fix the numpy support in ssbh_data_py to work with the updates to PyO3 before I can release the next ssbh_data_py update. It's also a good chance to look into making saving files that use numpy arrays faster in ssbh_data_py. I'll let you know when that is ready.

**Comment by ssbucarlos** [comment]
Sounds good!

**Comment by ScanMountGoat** [comment]
Version 0.7.1 is up now for ssbh_data_py. For Blender 3.3, make sure to extract the .whl files for python 3.10. There should be 4 total. We'll need to build pyprc for Apple Silicon at some point, but we can worry about that later. 

There are breaking changes, but it should be an easy fix. Let me know if you encounter any issues. @ssbucarlos 
https://github.com/ScanMountGoat/ssbh_data_py/releases/tag/0.7.1

**Comment by ScanMountGoat** [comment]
We should also get a noticeable speedup when exporting mesh files due to some internal improvements when working with numpy arrays.

**Comment by ssbucarlos** [comment]
Thank you for the update! atm im on vacation for the week, but when i return I'll get around to it.
Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by ssbucarlos** [comment]
Ok i am back and started working on this update. It seems like i need to also get 3.10 compatible pyprc files, and i think i figured out how to build them using maturin for windows, but i don't know how to build the linux / apple silicon files, so i need to look into that. Also on my end for pyprc it didn't build i think due to a breaking change that must have occured at some point in a dependency, so i need to test if the change i made in pyprc to get it to build didn't break it.

**Comment by ScanMountGoat** [comment]
What changes did you need to make? It looks like the dependencies are out of date on pyprc. We should be able to work with Arthur to get another release made with 3.10 support.

**Comment by ssbucarlos** [comment]
there was a to_hash40 that seemed to be removed, but it looks like changing it to just hash40 worked, and the read/set_custom_labels was removed at some point, so i copy pasted the following from paramxml and it looked like it worked,  i just tested it by making a new update.prc in smush_blender
![image](https://user-images.githubusercontent.com/77519735/199558852-9473d0d4-322f-4a07-a90f-57c11fde0edf.png)
Reaching out to the original owner of pyprc and helping them update it to support 3.10 would be ideal, i wasn't sure if pyprc was still maintained.

**Comment by ssbucarlos** [comment]
in the meantime since i got the windows version running i can handle addressing the breaking changes to ssbh_data_py / moving to ssbh_data_py for nuhlpb

**Comment by ssbucarlos** [comment]
Ok i think i took care of the breaking changes. I think it would be best to wait for the updated pyprc files before merging with main. i messaged arthur regarding 3.10 support
