### ISSUE TITLE
Bone controller’s 

### ISSUE THREAD

**Issue by puli2004** [ssbucarlos/smash-ultimate-blender#149]
This isn’t really a issue but more a suggestion. I feel that animating with controller bones would be much simpler then to just select each bone in controlling the character.
This is example of what I mean.
https://youtu.be/SBYb1YmaOMY

**Comment by ssbucarlos** [comment]
Now that the imported bones are better oriented for use in blender, you can use other plugins to setup controller bones or set them up manually. 
Setting up controller bones is outside the scope of this plugin.

**Comment by puli2004** [comment]
Ok good to know
