### ISSUE TITLE
Import swing.prc data

### ISSUE THREAD

**Issue by ssbucarlos** [ssbucarlos/smash-ultimate-blender#154]
**Motivation**
The current workflow for getting custom swing bones into the game is non-intuitive to a user and even if the user does know exactly what to do the task of measuring distances between bones, setting up collision shapes, fixing swing bone orientation, is fairly time consuming and is error-prone. Finally the task of formatting the `swing.prc` can be time consuming and is error-prone. Physics simulation is not planned in this update since more research is still required to figure out the extent that the in-game physics can be approximated in blender and how useful the limited simulation would even be.

**Goals**
- Visualize / Edit swingbone collision size
- Visualize / Edit collision shapes (Spheres, Ovals, Ellipsoids, Capsules, Planes)
- Visualize / Edit swing bone connections (useful for capes/skirts)
- Add utilities to convert existing bone chains to be proper Swing bones.
- Import/export swing.prc

**smush_blender changes**
- [ ]  Use pyprc to parse / write swing.prc
- [x]  Create swing.prc data UI panel (Armature -> Armature Data -> "Ultimate Swing Data")
- [ ]  Implement `swingbone` `collisionsizetip` & `collisionsizeroot` visualization / editing
- [ ]  Implement the following collision shapes visualization / editing / creation
- [ ]  1. `sphere` 
- [ ]  2. `oval` 
- [ ]  3. `ellipsoid` 
- [ ]  4. `capsule`
- [ ]  5. `plane`
- [ ]  Implement collision `connection` visualization / editing / creation
- [x]  Organize swing meshes in the scene collections
- [x]  Ignore swing meshes on model export
- [ ]  Implement operator to convert selected bones to be a valid ultimate swing bone chain. (Prefix 'S_', fix orientations, fix lengths, standardize names, add null bone)

**External changes**
- [x]  Push fixed param labels to remove known false-positive bone names. (remove 'colonel', replace with 'clavicle', etc.)
- [ ]  (Optional) Create PR to Improve QOL with pyprc (Export .pyi for type hints for qol in IDE)

**Comment by ScanMountGoat** [comment]
Fixing swing bone chains on export sounds like the only necessary change. The other points would still be nice to have. I don't think recreating the physics is worth it for things like wind or gravity. It would be nice to go through the swing bone files and at least document what each field does. The collisions should hopefully be more doable to recreate.

**Comment by ScanMountGoat** [comment]
All the bone name hashes should be up to date now on the param-labels repository for swing.prc files.
