### ISSUE TITLE
Smooth normals not always preserved on export

### ISSUE THREAD

**Issue by JArmstrongArt** [ssbucarlos/smash-ultimate-blender#163]
[Download Specimen of Files](https://github.com/ssbucarlos/smash-ultimate-blender/files/9759440/Specimen.zip)
Had this issue I was recommended to report yesterday.
So, I made this model in Blender 3.0. Upon exporting the model with this tool and then inspecting that export in StudioSB (I know this is an outdated program but this shouldn't be an issue in it even so), I noticed that faces along UV seams of the meshes had become triangulated strangely following a warning on export that some of my meshes were not triangulated and that this would be taken care of for me on export. This wouldn't be a problem if not for this automatic triangulation changing my shading from smooth to flat. I can only assume this happens along UV seams because it happened along the UV seam of the fluffy object I modelled and it happened along what I would assumed to be a reasonable UV seam for Banjo's hand. Below, you can see images demonstrating the effects of this issue from before export to after export.
![image](https://user-images.githubusercontent.com/47801313/195189593-66126521-813e-4001-9dc3-1d68c9cc6928.png)
![image](https://user-images.githubusercontent.com/47801313/195189606-ac4342a7-297f-44c2-98c2-ea865767727f.png)

**Comment by ssbucarlos** [comment]
Thanks for compiling the info, i should get around to looking into it sometime in the coming days, in the mean time, manually triangulate / split the mesh along the seams, and see if that fixes it. Theres some steps over on the wiki [here](https://github.com/ssbucarlos/smash-ultimate-blender/wiki/Read-this-if-you-have-export-issues.-Or-want-to-avoid-Export-Issues#uv-export-more-than-one-uv-coord-per-vertex), however it doesnt cover all cases.
I'll be updating this thread as i find more info.

**Comment by ScanMountGoat** [comment]
Check the render modes in SSBH Editor. StudioSB does not accurately render normals.

**Comment by JArmstrongArt** [comment]
I'll go download SSBH editor now and check on these files in there, it's worth a try, I just have not had any shading issues with any mesh in StudioSB thus far despite its age and inaccuracies.

**Comment by JArmstrongArt** [comment]
![image](https://user-images.githubusercontent.com/47801313/195194410-3232d009-713b-498d-abc0-1c37a55a6f59.png)
It's possible I'm mistaken, but it looks as though the issue persists in SSBH Editor. The rendering on all the meshes in terms of materials is completely off because this is from a version of the model before I worked around this issue for the time being and I no longer have the resources available to easily recreate those materials, but as far as I can tell smoothed normals should be apparent on the mesh even without a proper material to go along with it.

**Comment by ScanMountGoat** [comment]
Check the render modes under Menu > Render Settings. It's possible one of the vertex attributes or normal maps is causing the problem.

**Comment by ScanMountGoat** [comment]
For issues like this you would check Normals (includes normal maps) and Normal0 (mesh attribute).

**Comment by JArmstrongArt** [comment]
![image](https://user-images.githubusercontent.com/47801313/195202467-8bb6c6b1-f36c-456f-8cc0-2b011589bc85.png)
![image](https://user-images.githubusercontent.com/47801313/195202481-8b347e78-3bda-4068-80fb-a123d948c18d.png)
My apologies for misunderstanding, anyway, first picture is a look in 'Normals' mode, and the second picture is a look in 'Normal0' mode.

**Comment by JArmstrongArt** [comment]
Alright, well, for now I'll just enable auto-smooth, I have no faces on any of my meshes that require flat shading anyway. TY for giving this update!

**Comment by ScanMountGoat** [comment]
This is fixed now on the latest commit.
