### ISSUE TITLE
Normals transfer not working when splitting temp meshes on export

### ISSUE THREAD

**Issue by Ceruleancast** [ssbucarlos/smash-ultimate-blender#167]
I've been having an issue where when I export my model, the normals wind up getting messed up and a bright light wind up in areas they shouldn't be. First set of two images are pre export, the second set of two images are after the export.
Third set of two images are after pulling the vertices apart manually before exporting it, which seems to fix it(?)
Final image are the message logs I get after exporting it.
![image](https://user-images.githubusercontent.com/62217612/197250693-9b64c893-4dc0-451f-a436-5c13b97e7271.png)
![image](https://user-images.githubusercontent.com/62217612/197250706-020da9d2-3e35-4884-ba9a-fbcef7e21b23.png)
![image](https://user-images.githubusercontent.com/62217612/197250722-32f7ef52-cb78-41a3-a0bb-1dc91baff2d4.png)
![image](https://user-images.githubusercontent.com/62217612/197250734-b2f16110-ea15-4b7f-ab9a-c52f1aed7f5d.png)
![image](https://user-images.githubusercontent.com/62217612/197250749-25a295f1-5b4a-4304-93cc-ca98e91f02a9.png)
![image](https://user-images.githubusercontent.com/62217612/197250761-f19813f5-ede2-4faf-b362-257135e4e375.png)
![image](https://user-images.githubusercontent.com/62217612/197250767-b154797a-eb98-4d04-9ef4-323b8c539b96.png)

**Comment by ScanMountGoat** [comment]
Can you upload a zip with the blender file that you're trying to export? These kinds of issues are hard to fix just based on pictures.

**Comment by Ceruleancast** [comment]
https://www.dropbox.com/s/9obozr2zh23amv6/Shared%20Lina%20files.7z?dl=0

**Comment by ScanMountGoat** [comment]
The addon sometimes needs to split edges to ensure vertices are indexed properly to work with Smash Ultimate's mesh format. This is necessary and can only be done reliably by the tool on export. We also apply a data transfer modifier to the temporary mesh that gets exported to try and preserve the smooth shading. This seems to be causing issues. 

I can reproduce this by duplicating the clothes mesh and then applying a data transfer modifier in Blender. The only mapping that seems to work is `TOPOLOGY`, but this won't work after we split edges. The normal transfer seems to be unreliable and tweaking the ray casting parameters doesn't help much. I'll need to look into if there's a better way of doing this. We should be able to copy the old custom normals using BMESH or the regular mesh.data API only for the split edges and avoid the issues with data transfer. I'll try and look into this later unless you want to make an attempt at it @ssbucarlos.

You can always split the edges yourself for now, but it's not always obvious which edges need to be split.

**Comment by ssbucarlos** [comment]
Ill take a look at it later today

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by Ceruleancast** [comment]
I'll see what I can do to make it look nicer, and if I can't figure it out well I can always work on the rest that I still need to finish up on my wip mod I suppose on the meantime instead.

**Comment by ssbucarlos** [comment]
> We should be able to copy the old custom normals using BMESH or the regular mesh.data API only for the split edges and avoid the issues with data transfer

@ScanMountGoat Since the data transfer modifier accepts a vertex group as a filter, i can add a new vertex group and add only the verts that are gonna be split to it, and then use that new group as the filter for the data transfer modifier. This should work for now, although i would like to also eventually find a better solution long-term that doesn't need this modifier.

**Comment by ScanMountGoat** [comment]
That should work for now. We can make a separate issue to track it for later.

**Comment by ssbucarlos** [comment]
![image](https://user-images.githubusercontent.com/77519735/197315984-cbe75782-0b77-44ac-abcd-ea0ac1d90a51.png)
![image](https://user-images.githubusercontent.com/77519735/197316153-43981665-5485-407c-a9e8-67a9fe2665bc.png)

This is what the normal0 and shaded export looks like on the issue branch. Left is main and right is issue branch. Theres potentially other issues with the shading but it doesnt seem to be related to the mesh normals
