### ISSUE TITLE
Check for addon updates

### ISSUE THREAD

**Issue by ScanMountGoat** [ssbucarlos/smash-ultimate-blender#171]
There's currently no way for users to know if they're on the latest version. It's not uncommon for a user to believe the installed version is the latest even if it is months out of date. Automatically downloading and installing updates won't work properly since the native python modules can't be replaced without restarting Blender. We should still be able to check if there are any updates available from github. There are a number of components required for this to work.
- [x] number or version releases (release tags?)
- [ ] add a button for users to check github if there is a newer version (do this automatically?)
- [ ] keep a changelog.md (optional)

**Comment by ssbucarlos** [comment]
This is for sure something thats needed, so ill look into it after the swing.prc import stuff is finished. With the swing.prc we can make that release 1.0.0 for version checking. Ideally i would like to automatically check for the update without blocking the application, maybe there can be a panel that automatically shows up only when theres an update detected. I'll also add a button to manually check for updates.

**Comment by ScanMountGoat** [comment]
There's obviously not a right or wrong way to do it, but a common format for changelogs can be found at [Keep a Changelog](https://keepachangelog.com/en/1.0.0/). Some repos have [very detailed changelogs](https://github.com/gfx-rs/wgpu/blob/master/CHANGELOG.md) and others are [more basic](https://github.com/ScanMountGoat/ssbh_editor/blob/main/CHANGELOG.md). This is an application and not a library that other people depend on, so I wouldn't worry too much about how to handle the version numbering.

If we want people to be notified of updates occasionally, we can just use git tags. You can create a git tag when creating or update a release or manually through the command line. We would use tags like "1.0.0" to compare versions with the current version stored in the addon info file. We can also just download and parse the info file off of github and compare the version string, but it might be nice to be able to see which commits go with each version tag on github.

For daily updates or on each commit, I'm not sure if there's an easy way to do that. We would need to store the current commit hash or find a way to compare the time a user downloaded the addon with the time of the most recent commit. I'm not sure how much development we'll be doing on a daily basis after the 1.0.0 release, so this might not be worth the effort.

**Comment by ScanMountGoat** [comment]
> This is for sure something thats needed, so ill look into it after the swing.prc import stuff is finished. With the swing.prc we can make that release 1.0.0 for version checking. Ideally i would like to automatically check for the update without blocking the application, maybe there can be a panel that automatically shows up only when theres an update detected. I'll also add a button to manually check for updates. Im not familiar with keeping a changelog.md but ill look into that too

The basic logic is to show the update if the local version string is less than the online version. The local version we can either store in a variable on startup from the bl_info or try and get dynamically using the addon_utils version. The online version will be checked from github. I would recommend just finding the latest release tag since people probably don't need the latest commit. 

The code linked below works in Blender from my testing. The github API has rate limits, but it's unlikely that people will hit them by opening Blender that many times. We can always handle any errors by displaying them to the user or just treating a failed request as no update available.
https://stackoverflow.com/questions/60716016/how-to-get-the-latest-release-version-in-github-only-use-python-requests

If an update is available from the check above, we can download and parse the changelog. An easy way to do it that is to order the changelog from most recent to least recent and just get the substring from the current version tag in the markdown to the start of the file.
