### ISSUE TITLE
Import materials fails on Blender 3.4

### ISSUE THREAD

**Issue by Coffiend** [ssbucarlos/smash-ultimate-blender#176]
After upgrading to the latest version of Blender and this plugin, I receive the following error when importing a model

![Capture](https://user-images.githubusercontent.com/93229540/206952915-6a5545f0-4a33-4677-863c-1999679dce88.PNG)

**Comment by ScanMountGoat** [comment]
It's working fine for me after installing the latest version of the addon on Blender 3.3.1. What version of Blender are you using?

**Comment by Coffiend** [comment]
I'm using Blender 3.4.0

Also, I tried using the Reimport Materials option this morning and got this message. Hopefully it's related to the root of whatever my issue is 
![image](https://user-images.githubusercontent.com/93229540/207054420-db9e9d59-90d0-427e-9a6a-397151ffa2b7.png)

**Comment by Coffiend** [comment]
I neglected to say that, clicking on the import button after the initial failure brought in the model with unassigned and empty materials 
![image](https://user-images.githubusercontent.com/93229540/207056615-69e16b0e-1260-456d-a17e-14f353907852.png)
![image](https://user-images.githubusercontent.com/93229540/207056821-57ac04ad-1f9b-4685-8d6f-c1856668d896.png)
![image](https://user-images.githubusercontent.com/93229540/207056895-ed5f7f11-3df7-4325-9090-045840f32956.png)

**Comment by ScanMountGoat** [comment]
It looks like only the material import failed. I haven't tested the addon yet on Blender 3.4. Do you still get this error if you try it on Blender 3.3?

**Comment by Coffiend** [comment]
Nope! All is good in Blender in 3.3

**Comment by ScanMountGoat** [comment]
I'm no longer getting this error on 3.4 on the latest commit. Linking this discussion for future reference. Apparently inputs/outputs need to be added to the node_tree and not the node itself, despite this not being mentioned anywhere on the changelog or the original issue.
https://developer.blender.org/T100770
