### ISSUE TITLE
Textures not importing

### ISSUE THREAD

**Issue by NathanBWaters** [ssbucarlos/smash-ultimate-blender#177]
I believe the purple means the textures didn't load in Blender

![image](https://user-images.githubusercontent.com/4016602/211171908-82fda484-d00d-4599-9b29-37e194bf2866.png)

I'm not seeing any issues when loading the same folder in SSBH Editor:
![image](https://user-images.githubusercontent.com/4016602/211172729-f4d15c23-8ec3-416a-be53-2f2cea0401d4.png)

Since I opened Blender in the command line, I'm seeing `GPUTexture: Blender Texture Not Loaded!`.

Is this due to the Known Limitations in https://github.com/ssbucarlos/smash-ultimate-blender/wiki/Known-Blender-Issues that says?

> Textures 2,3,7,13 are not previewed.

I don't believe that's the issue since it seems [Texture0,Texture1 are the albedo files](https://scanmountgoat.github.io/Smush-Material-Research/textures/col/). 

Or is this due to me needing to convert `.nutexbs` to `.png` files like it says [here](https://github.com/ssbucarlos/smash-ultimate-blender/issues/139)?  It seems that the tool used for this is Switch-Toolbox but I believe it's Windows only.  Does that mean I should go with using a Rust nutexb crate like I'm seeing [here](https://docs.rs/nutexb/latest/nutexb/) to create the .png files?  I haven't tried using Rust before but I think I could write a script to convert all `.nutexb` files to `.png`.

What are the steps for fixing this error? 

I'm on an M1 Mac and using Blender 3.3.2.  

First time getting into the Smash modding space so apologies if this is a noob question.

**Comment by ScanMountGoat** [comment]
You'll need to convert the textures to PNG in order for Blender to load them. The addon will still work proprely without the textures, you just won't get the texture previews in the viewport or renders. The addon only cares about the texture paths for exporting materials in the numatb. You can always fix the texture assignments later in SSBH Editor. SSBH Editor is using the graphics capabilities of the M1 chip and doesn't require any external programs for converting the textures. 

There aren't any tools that I'm aware of that can convert DDS files to and from PNG for MacOS. I'd like to create a conversion program at some point that also works Linux and MacOS. The code all exists already, but there's some work involved to get it compiling on all platforms.

You'll need find some other way to load the textures in Blender for now. You can convert the nutexb files to DDS using the code you linked, but you'll have to compile it yourself. Blender doesn't support the BC7 compression format used by most textures in Ultimate, so you'll also need to convert these DDS files to PNG. I've found that the preview app on MacOS seems to work. I don't believe there's a way to convert the PNG files back to DDS on Mac without compiling a BCN compression program.

**Comment by NathanBWaters** [comment]
Thanks for the all the great info and quick response!  I'll use nutexb_cli tool to convert from Nutexb to DDS, and then will find another tool to convert DDS to PNG.  Perhaps imagemagick will do the trick.

> You can always fix the texture assignments later in SSBH Editor.

Am I understanding you correctly that I would use the SSBH Editor to re-write the `.numatb` file so that it uses a png?  I put in a random .png file called `poster.png` in the folder with the other model.* files and SSBH Editor doesn't seem to be picking it up.  If I switch to Advanced Settings and type in `poster.png` that also doesn't work.

![image](https://user-images.githubusercontent.com/4016602/211174256-ce257efe-1efd-47e0-a3a1-0b89773b02d8.png)

![image](https://user-images.githubusercontent.com/4016602/211174278-18cbd0b7-b3b9-4da8-94d1-9ebd7d1901c1.png)

I read through the [Matl Editor doc](https://github.com/ScanMountGoat/ssbh_editor/wiki/Matl-Editor) but let me know if there's other documentation on how to do this.

For context, I'm trying to build up a Smash Ult dataset for AI training.  So I want to export every animation for every character with every skin from various camera angles.  I was hoping to do this in Blender in order to automate the process but let me know if you think SSBH Editor would be a better tool to do so since it already has `Render Animation > Render to Gif`.

Thanks for making such great tools!

**Comment by ScanMountGoat** [comment]
> Am I understanding you correctly that I would use the SSBH Editor to re-write the `.numatb` file so that it uses a png? I put in a random .png file called `poster.png` in the folder with the other model.* files and SSBH Editor doesn't seem to be picking it up. If I switch to Advanced Settings and type in `poster.png` that also doesn't work.

SSBH Editor is the preferred application for editing materials. The material export in Blender is mostly for handling the assignment of materials and textures since this is a bit tedious to do manually in SSBH Editor. If you assign "my_texture.png" in Blender, the addon will export a material in the numatb that assigns texture "my_texture". The numatb texture paths don't include file extensions since all model textures in game must use nutexb.

> For context, I'm trying to build up a Smash Ult dataset for AI training. So I want to export every animation for every character with every skin from various camera angles. I was hoping to do this in Blender in order to automate the process but let me know if you think SSBH Editor would be a better tool to do so since it already has `Render Animation > Render to Gif`.

SSBH Editor is probably the easier option. SSBH Editor has more game accurate model and animation rendering than Blender. If you want the renders to look pretty, I would put in the extra work to set up scenes in Blender and render with Cycles or Eevee. You can't script SSBH Editor, but you can download the code and modify it locally to do what you want. Blender can be used from command line like you mentioned, but it may end up being just as much work.

**Comment by ScanMountGoat** [comment]
I would also look into using ssbh_wgpu, which is the renderer used by SSBH Editor. One of the example projects already does almost exactly what you want. https://github.com/ScanMountGoat/ssbh_wgpu/blob/main/ssbh_wgpu_test/src/main.rs

**Comment by NathanBWaters** [comment]
Thanks so much!  I'll try out the sample script you linked.  🚀

**Comment by NathanBWaters** [comment]
Updated the script so it now exports all characters, all skins, all animations, from multiple angles.  Thanks again @ScanMountGoat!

**Comment by ScanMountGoat** [comment]
Great!
