### ISSUE TITLE
Normals/Shading Export Issue

### ISSUE THREAD

**Issue by BeverageGaming** [ssbucarlos/smash-ultimate-blender#178]
I believe I have found an issue with exporting models on the latest version. It seems that exporting models causes their normals to get messed up. Here are some comparison images of models exported using the old branch vs the main branch as seen in SSBH.

![the_old](https://user-images.githubusercontent.com/45641125/211398327-97a2424c-9807-46d7-8d83-f1d8f72f4a1d.png)
![the_new](https://user-images.githubusercontent.com/45641125/211398346-b48a3849-dbb3-450d-945c-89ea3f873f10.png)
![a](https://user-images.githubusercontent.com/45641125/211398355-bb8fc0a4-8314-47fe-ae7b-fda12e253695.png)
![b](https://user-images.githubusercontent.com/45641125/211398372-a5054485-fda0-4fee-ab3c-f5d290a9dce9.png)
![a2](https://user-images.githubusercontent.com/45641125/211398384-177236fa-6160-4804-8857-f25a878c1261.png)
![b2](https://user-images.githubusercontent.com/45641125/211398401-28d4e825-07e1-49ba-8a46-94ada70a3db5.png)

**Comment by BeverageGaming** [comment]
They are custom models.
Here are the blend files:
https://drive.google.com/drive/folders/1ujO9eSOT8aWHHaVdJ3hQ8pPXeq-9qwCc?usp=sharing

**Comment by ScanMountGoat** [comment]
There were some recent changes to normals export to solve the accuracy issues with using a data transfer modifier. The current version isn't correctly accounting for unapplied transforms. This is an easy fix on our end. Just apply all the transforms before export for now as a temporary workaround.

**Comment by ScanMountGoat** [comment]
Fixed on the latest commit.
