### ISSUE TITLE
Apply Transforms on Export

### ISSUE THREAD

**Issue by ssbucarlos** [ssbucarlos/smash-ultimate-blender#18]
Currently the user needs to always make sure they apply all transforms (Loc Rot Scale) before exporting a model. Ideally this should be automatic

**Comment by ScanMountGoat** [comment]
There are a number of ways of doing this. It might be more reliable to apply the bone transform immediately on import and then decide at export time if the single bind optimization can be applied (check that a single bone has all 1.0's for it's weights).
```python
# Transform the vertices themselves rather than setting the object transform.
# This ensures single bound meshes export correctly with normal skin weights.
mesh_obj.data.transform(get_matrix4x4_blender(world_transform))
mesh_obj.data.update()
```

**Comment by ScanMountGoat** [comment]
Applying mesh transforms is already implemented on the current version.
