### ISSUE TITLE
Material Import fails in Blender 3.4.1

### ISSUE THREAD

**Issue by Malik177** [ssbucarlos/smash-ultimate-blender#186]
Every time I try to export my modified Zelda model it keeps saying a material has not been registered. And when I try to make a new meterial for the all the parts of the model a new error pops up a long with it. Can you investigate this when you have a chance?

**Comment by ssbucarlos** [comment]
Please provide screenshots of the errors you are experiencing. 
Also, smush_blender may provide a warning but it should still let you export, you will just need to fix ur materials in ssbh_editor

**Comment by Malik177** [comment]
ok ill send some screenshots of it when I can. Also, the thing is all I really did was just did was remove the cape geometry that the Zelda model has. Everything on the model should be normal since I never changed anything besides just that.

**Comment by ssbucarlos** [comment]
I just removed the cape and was able to export without warnings.
![image](https://user-images.githubusercontent.com/77519735/227752571-56fc51ef-f9fa-4033-a64c-a725e6b1fb02.png)
![image](https://user-images.githubusercontent.com/77519735/227752594-3007ffc2-8167-4c9e-925a-48a348162e8e.png)

**Comment by Malik177** [comment]
im really confused on why this happening to me maybe its the blender version im using. I'm using v3.4.1

**Comment by Malik177** [comment]
ima upload the screenshot now

**Comment by Malik177** [comment]
oh never mind I figured it out its was because of the blender version im using.

**Comment by Malik177** [comment]
but how do you get the texture to show up?

**Comment by Malik177** [comment]
![Screenshot (554)](https://user-images.githubusercontent.com/90985970/227753712-92e317b8-18bc-4ba6-b34a-f17bb8ea6abd.png)

**Comment by ssbucarlos** [comment]
> oh never mind I figured it out its was because of the blender version im using
I will go test on 3.4.1 then

**Comment by Malik177** [comment]
ok

**Comment by ssbucarlos** [comment]
> but how do you get the texture to show up?

Convert the .nutexbs to .png

**Comment by Malik177** [comment]
alright

**Comment by ssbucarlos** [comment]
![image](https://user-images.githubusercontent.com/77519735/227754077-a1753954-b7ab-4bc4-8674-faf3819a264e.png)
looks like material import is broken in 3.4 xd, thanks for making the issue, ill look into fixing it

**Comment by Malik177** [comment]
alright atleast this issue report turned out useful lol.

**Comment by ssbucarlos** [comment]
Ok i just fixed it, can u download the latest and late me know if it works now

**Comment by Malik177** [comment]
ok i can do that later I have to go sleep

**Comment by ssbucarlos** [comment]
yeah theres no rush, if the issue persists i can reopen this later
