### ISSUE TITLE
Animations fail to import if from SSBU file dump

### ISSUE THREAD

**Issue by osliecranwave** [ssbucarlos/smash-ultimate-blender#196]
Basically I want to import an animation from the file dump below because I don't know how to dump files myself https://mega.nz/#F!AAwWzCjT!Zd5kKpuQcE647DSRtpFShw

But when I import in any one of the files, this error appears.
<img width="865" alt="Screenshot 2023-07-07 at 14 24 14" src="https://github.com/ssbucarlos/smash-ultimate-blender/assets/138881362/6ca98fdc-0985-4ee2-bb71-e5d3e75b37d0">

I have no idea what's causing this.

**Comment by ssbucarlos** [comment]
Try it on blender 3.3+

**Comment by osliecranwave** [comment]
the problem still happens even on 3.6.

**Comment by ssbucarlos** [comment]
re-download, re-install on blender 3.3+ and try again. the line number from the error seems to indicate an out-of-date version

**Comment by osliecranwave** [comment]
the plugin? or blender itself?

**Comment by osliecranwave** [comment]
I reinstalled the plugin and it works! Thank you for your help!
