### ISSUE TITLE
"Vertex index 112700 exceeds the limit of 65535 for mesh"

### ISSUE THREAD

**Issue by AronTW** [ssbucarlos/smash-ultimate-blender#197]
I'm getting this error when exporting a custom model I have to go over Sonic, I don't know what to about it, any help?
![image_2023-07-12_184930205](https://github.com/ssbucarlos/smash-ultimate-blender/assets/127395319/4b116f7a-f331-4e9a-9b72-4b01667b25e1)

**Comment by ScanMountGoat** [comment]
The error message lists potential ways to fix it. There are limits for how many unique vertices each mesh can have in game.

**Comment by AronTW** [comment]
> The error message lists potential ways to fix it. There are limits for how many unique vertices each mesh can have in game.

How exactly do I reduce the amount of vertices?

**Comment by ScanMountGoat** [comment]
The easiest is to just split the mesh into multiple meshes either by material or by loose parts. You can also try merging duplicate vertices by distance. A mesh with over 100000 vertices seems high for Smash Ultimate. I would make sure that the polygon and vertex counts are similar to the in game models to avoid any unwanted lag.

**Comment by AronTW** [comment]
> The easiest is to just split the mesh into multiple meshes either by material or by loose parts. You can also try merging duplicate vertices by distance. A mesh with over 100000 vertices seems high for Smash Ultimate. I would make sure that the polygon and vertex counts are similar to the in game models to avoid any unwanted lag.

What polygon count do I shoot for?

**Comment by ScanMountGoat** [comment]
It depends on the character. If you have multiple meshes with that many vertices, it won't perform well. If that's the only mesh, it might be fine after splitting. You can import the in game models with the Blender addon to see how many polygons are typically used.
