### ISSUE TITLE
Issues with animations

### ISSUE THREAD

**Issue by Escope12** [ssbucarlos/smash-ultimate-blender#201]
Hi. I'm trying to backport stage animations from Smash Ultimate into Brawl but when I import them onto the BrawlCrate .dae model, this happens. 
![image](https://github.com/ssbucarlos/smash-ultimate-blender/assets/8963276/6642ac2c-1e0e-4295-a1ce-9b616ad8d4ca)

**Comment by ssbucarlos** [comment]
Officially the plugin is for ultimate modding, the animation importer is meant to import .nuanmbs onto ultimate models also imported with this plugin. I wont be able to provide good help with your specific backporting workflow. To determine if this is really an issue with the plugin, please try importing the .nuanmb animation over the original ultimate stage. If it works, that means the issue isn't with the plugin, but rather an issue with the setup. Stuff like different bone names in the brawl skel could make it seem like nothing is happening.

**Comment by Escope12** [comment]
I can try that. It looks fine when I import the original Ultimate model and for some reason when I exported that model as smd and import it to maya, the z rotation was at -90.

**Comment by ssbucarlos** [comment]
If you export as .smd (or any other non-ultimate format) using another plugin i can't help out with those issues since i have no experience with those formats / workflows / usecases / plugins

**Comment by Escope12** [comment]
Ok. Thanks anyway
