### ISSUE TITLE
Making combined new skeleton causes error.

### ISSUE THREAD

**Issue by JerryDELUXE** [ssbucarlos/smash-ultimate-blender#209]
This is the error it causes:

Python: Traceback (most recent call last):
  File "/home/deck/.var/app/org.blender.Blender/config/blender/4.0/scripts/addons/smash-ultimate-blender/modules/exo_skel.py", line 278, in execute
    exo_group = new_arma.pose.bone_groups.get('Exo Skel')
AttributeError: 'Pose' object has no attribute 'bone_groups'

Also when I tried to test an animation after parenting the H_Exo_trans bone to the hip bone it looked like this:

![Screenshot_20231126_174351](https://github.com/ssbucarlos/smash-ultimate-blender/assets/146459906/daabdd2d-b8b2-4669-9cd7-8d687353654b)

I don't know if what happened in the image is related.

**Comment by ssbucarlos** [comment]
Oops, shouldnt take too long to fix, ill get around to it today

Sent from my T-Mobile 5G Device
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: JerryDELUXE ***@***.***>
Sent: Sunday, November 26, 2023 9:50:46 AM
To: ssbucarlos/smash-ultimate-blender ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ssbucarlos/smash-ultimate-blender] Making combined new skeleton causes error. (Issue #209)


This is the error it causes:

Python: Traceback (most recent call last):
File "/home/deck/.var/app/org.blender.Blender/config/blender/4.0/scripts/addons/smash-ultimate-blender/modules/exo_skel.py", line 278, in execute
exo_group = new_arma.pose.bone_groups.get('Exo Skel')
AttributeError: 'Pose' object has no attribute 'bone_groups'

Also when I tried to test an animation after parenting the H_Exo_trans bone to the hip bone it looked like this:

Screenshot_20231126_174351.png (view on web)<https://github.com/ssbucarlos/smash-ultimate-blender/assets/146459906/daabdd2d-b8b2-4669-9cd7-8d687353654b>

I don't know if what happened in the image is related.
