### ISSUE TITLE
Crashing whenever moving frames

### ISSUE THREAD

**Issue by dungerus** [ssbucarlos/smash-ultimate-blender#217]
After importing an animation, when I try to manually go to a certain frame of an animation, or whenever the animation loops and resets back to the first frame, blender instantly closes and I cannot find why, is it a known issue or is there a known fix?

**Comment by ssbucarlos** [comment]
i cannot replicate the issue and haven't heard about this before. Please let me know what operating system you are on, and what blender version you are on, and if you have observed any other crashes in blender, maybe while rendering or while playing other animations.
________________________________
From: dungerus ***@***.***>
Sent: Wednesday, December 27, 2023 4:31 AM
To: ssbucarlos/smash-ultimate-blender ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ssbucarlos/smash-ultimate-blender] Crashing whenever moving frames (Issue #217)


After importing an animation, when I try to manually go to a certain frame of an animation, or whenever the animation loops and resets back to the first frame, blender instantly closes and I cannot find why, is it a known issue or is there a known fix?
