### ISSUE TITLE
Model exporting with mesh rotated incorrectly

### ISSUE THREAD

**Issue by Superjosh00** [ssbucarlos/smash-ultimate-blender#218]
Hi im looking to make a moveset using a model from a dumped game, but when i attempt to export it using the plugin it results in the mesh and skeleton not lining up whatsoever which then causes any animation to be completely broken. This model does seem to work fine in other programs (ive tried so far godot, noesis, & pixelover) so im not sure what could be causing this.
 (img 1 is blender which is what it relatively should look like, img 2 is ssbh editor)
![image](https://github.com/ssbucarlos/smash-ultimate-blender/assets/54812969/b42439e2-92e1-48f9-9e5d-e7b94e9bb17e)
![image](https://github.com/ssbucarlos/smash-ultimate-blender/assets/54812969/37c98e8a-80f0-4976-b3b4-27d5b45082d6)

**Comment by ssbucarlos** [comment]
Id try removing any empty objects in ur model heirarchy (theres at least one at the root), applying all transforms, and trying again and seeing if ur model exports correctly

Sent via the Samsung Galaxy S22 Ultra 5G, an AT&T 5G smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Superjosh00 ***@***.***>
Sent: Sunday, December 31, 2023 3:31:46 PM
To: ssbucarlos/smash-ultimate-blender ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ssbucarlos/smash-ultimate-blender] Model exporting with mesh rotated incorrectly (Issue #218)


Hi im looking to make a moveset using a model from a dumped game, but when i attempt to export it using the plugin it results in the mesh and skeleton not lining up whatsoever which then causes any animation to be completely broken. This model does seem to work fine in other programs (ive tried so far godot, noesis, & pixelover) so im not sure what could be causing this.
(img 1 is blender which is what it relatively should look like, img 2 is ssbh editor)
image.png (view on web)<https://github.com/ssbucarlos/smash-ultimate-blender/assets/54812969/b42439e2-92e1-48f9-9e5d-e7b94e9bb17e>
image.png (view on web)<https://github.com/ssbucarlos/smash-ultimate-blender/assets/54812969/37c98e8a-80f0-4976-b3b4-27d5b45082d6>

**Comment by Superjosh00** [comment]
i didint know about applying transforms before, so i selected the hierarchy of the imported model (the root of it) and did apply all transforms through Object -> Apply -> All Transforms. when i do this though it appears to break the model in blender at least (img1)


when i export the model after doing this and open in ssbhe it does appear to have worked somewhat (img2), but when trying to play an animation (exported after applying transforms) everything breaks (img3)


![image](https://github.com/ssbucarlos/smash-ultimate-blender/assets/54812969/b9a41ccf-0f46-48f3-af7b-e1c4b762b514)
![image](https://github.com/ssbucarlos/smash-ultimate-blender/assets/54812969/d83461ad-aae4-40c4-ade8-8e41a62fd185)
![image](https://github.com/ssbucarlos/smash-ultimate-blender/assets/54812969/1f54b713-d774-45b6-98b7-a25942f578b3)

**Comment by ssbucarlos** [comment]
Theres still alot of empty objects in the model heirarchy. It will be up to you to figure out how to simplify what you currently have down to just one armature. You will then also need to figure out how to "bake" the final animation you see in blender such that it works with just the one armature without needing all the empties.
![image](https://github.com/ssbucarlos/smash-ultimate-blender/assets/77519735/36280598-b534-4a9b-bbb7-4f36d96dec60)
