### ISSUE TITLE
Misc. "Eye Material Custom Modal Operator" doesn't work anymore

### ISSUE THREAD

**Issue by Nixoup** [ssbucarlos/smash-ultimate-blender#219]
Hello,
After a few projects using this feature, it stopped working. Not being very comfortable with Blender, I admit to being completely stuck.
I try to use the "Sprite Sheet Params" in "Shading" but even it refuses to move the eyes.

![Capture](https://github.com/ssbucarlos/smash-ultimate-blender/assets/78208484/15e7cfb5-5e64-4567-8458-ff599f5819db)

A solution? (I'm on Blender 3.6)

**Comment by ssbucarlos** [comment]
i dont know why it would stop working, i havent made any changes to the uploaded 3.6 release. try a fresh 3.6 project and it should work as usual

Sent via the Samsung Galaxy S22 Ultra 5G, an AT&T 5G smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Nixop ***@***.***>
Sent: Saturday, January 27, 2024 1:33:36 PM
To: ssbucarlos/smash-ultimate-blender ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ssbucarlos/smash-ultimate-blender] Misc. "Eye Material Custom Modal Operator" doesn't work anymore (Issue #219)


Hello,
After a few projects using this feature, it stopped working. Not being very comfortable with Blender, I admit to being completely stuck.
I try to use the "Sprite Sheet Params" in "Shading" but even it refuses to move the eyes.

Capture.PNG (view on web)<https://github.com/ssbucarlos/smash-ultimate-blender/assets/78208484/15e7cfb5-5e64-4567-8458-ff599f5819db>

A solution? (I'm on Blender 3.6)

**Comment by ssbucarlos** [comment]
![image](https://github.com/ssbucarlos/smash-ultimate-blender/assets/77519735/a55c500b-d7a4-4736-a491-cc2ad6b1aea3)
The modal still worked on 3.6 for me
