### ISSUE TITLE
Blender 4.1 support

### ISSUE THREAD

**Issue by ScanMountGoat** [ssbucarlos/smash-ultimate-blender#221]
I haven't tested the beta yet to see how much of this impacts our code. Blender is changing it's Python version from 3.10 to 3.11, so we'll need to create a new release that is no longer compatible with earlier versions. The release is supposed to be in a little over a week on March 19th.
https://developer.blender.org/docs/release_notes/4.1/python_api/

I've already published ssbh_data_py [0.8.2](https://github.com/ScanMountGoat/ssbh_data_py/releases/tag/0.8.2) with support for Python 3.11, so we can just unzip the whl files for each target. There aren't any API changes. I've made an issue on PyPrc to add support for newer Python versions. We'll probably end up needing to build PyPrc from source to support Python 3.11. I can build the MacOS builds on my M1 machine if needed.

**Comment by ssbucarlos** [comment]
The builds of pyprc would be super helpful. i will try to get around to addressing the breaking blender changes tomorrow as i think theres a few

**Comment by ssbucarlos** [comment]
ok i at least figured out how to build the windows version of pyprc for python 3.11, ill continue some more tomorrow

**Comment by ScanMountGoat** [comment]
I can add builds for Linux and macos later.

**Comment by ssbucarlos** [comment]
ok i got a branch with 4.1 support made

**Comment by ScanMountGoat** [comment]
I'm having trouble cross compiling PyPrc for x86 on my MacBook Air. I'll try and update the pyo3 version on a fork later today and see if that works. I should also be able to add a linux build for Python 3.11.

**Comment by ScanMountGoat** [comment]
Linux and MacOS builds have been updated now. The branch works on MacOS other than the permission issues with ultimate_tex_cli. I don't know if there's an easy way to fix that.

**Comment by ssbucarlos** [comment]
bless 🙏
