### ISSUE TITLE
gltf/glb exports do not include textures

### ISSUE THREAD

**Issue by 100Rings** [ssbucarlos/smash-ultimate-blender#224]
Perhaps I am doing something wrong but I have tried everything and nothing seems to work. No matter what I do, models exported as gltf display as grayscale with none of the textures that I added in blender.

**Comment by ScanMountGoat** [comment]
The smash-ultimate-blender addon uses a custom material node setup that isn't supported by any export format like gltf or fbx. The emission is being incorrectly set to white and hiding the textures when I tested with Mario c00. You'll need to recreate all the materials with a regular principled BSDF shader following the setup expected by the gltf addon.
https://docs.blender.org/manual/en/2.80/addons/io_scene_gltf2.html#exported-materials

**Comment by ssbucarlos** [comment]
Closing since SMG provided helpful info already and also the gltf exporter (or any other exporter) is not something this plugin has control over

**Comment by 100Rings** [comment]
> The smash-ultimate-blender addon uses a custom material node setup that isn't supported by any export format like gltf or fbx. The emission is being incorrectly set to white and hiding the textures when I tested with Mario c00. You'll need to recreate all the materials with a regular principled BSDF shader following the setup expected by the gltf addon. https://docs.blender.org/manual/en/2.80/addons/io_scene_gltf2.html#exported-materials

Thank you
