### ISSUE TITLE
Textures not importing on MacOS.

### ISSUE THREAD

**Issue by ZenoTheWatermelon** [ssbucarlos/smash-ultimate-blender#228]
Tried importing sonic model, double checked .nutexb files were present, yet they didnt import. Not at all an experienced blender user or programmer so am very lost.

**Comment by ssbucarlos** [comment]
hey zeno, sorry for the inconvenience but atm thats due to something out of our control on MacOS, please refer to https://github.com/ssbucarlos/smash-ultimate-blender/issues/213 for info on how to manually set ultimate_tex as executable so that the texture conversion can work.

**Comment by ZenoTheWatermelon** [comment]
alright thanks
