### ISSUE TITLE
StructRNA of type Object has been removed

### ISSUE THREAD

**Issue by edouardberger** [ssbucarlos/smash-ultimate-blender#229]
Hi, I'm very new to this, so i'm probably missing something very obvious, but i searched everywhere and can't find a solution.
Maybe it's not even related with the code itself and i just do something wrong.
When exporting an Arsene model (modified, vanilla and any type of model actually) i get this (screenshot)

<img width="964" alt="Capture d’écran 2024-12-05 à 21 37 54" src="https://github.com/user-attachments/assets/3b1d355d-eceb-4da6-9fee-7b07134a0ef3">

Any idea how i can fix this (again im a newbie so it might be very obvious)?

Thank you very much

Ps : Im on Macbook pro M3 ; OS 15.1.1 ; Blender 4.2.4 ; latest smash_ultimate_blender

**Comment by ScanMountGoat** [comment]
Do you get this error if you export arsene's vanilla model without any edits?

**Comment by edouardberger** [comment]
Yes !

**Comment by edouardberger** [comment]
Oh and since i have a Apple Silicon, i marked ultimate_tex_cli as executable through Terminal like ScanMountGoat mentioned in another issue, and changed manually the path from Blender 4.0 to 4.2 since it the script seemed to be made for Blender 4.0. I don't think its related but since i know nothing, we never know lmao

**Comment by ScanMountGoat** [comment]
I don't get that error on Blender 4.3 when importing `fighter/jack/model/doyle/c00` and exporting again with default settings on either Windows 11 or my M1 Mac. Do you get this error with all models or just Arsene?

**Comment by edouardberger** [comment]
Imma try right now

**Comment by ScanMountGoat** [comment]
It looks like Blender is trying to process an object that is already deleted. I would try launching Blender with a new scene and see if that works. It may also be an issue with your specific Blender version. Weird things like this have happened for people in the past.

**Comment by edouardberger** [comment]
Thank you very much for your time, i really appreciate it
imma continue to try few things on my own

**Comment by edouardberger** [comment]
So yeah it does the same for other models (tried kazuya and it does the same thing).
The thing that made me go for blender 4.2 was the XNALaraMesh XPS tool (which i think it doesn't work on 4.3), since the model i use to replace Arsene was a XPS.
I will try with different Blender versions i let you know

**Comment by edouardberger** [comment]
YOU WERE RIGHT. Changed to blender 4.3 and it worked for vanilla model (import and export). 
Will try with modified model tomorrow.
btw I asked my friend ChatGPT about this and he said it probably was Blender API interacting weirdly with the script
again thank you for your time

**Comment by edouardberger** [comment]
Everything works. Got a nice Thanatos replacing Arsene 
Thank you very much, you the goat (litterally) <3
