### ISSUE TITLE
Display a dialog box with error details + possible solutions, rather than outputting partial assets when there is an error

### ISSUE THREAD

**Issue by ssbucarlos** [ssbucarlos/smash-ultimate-blender#23]
Currently, when theres an issue, the script might output only some of the files, giving an unfamiliar user the wrong idea. In addition, it can be hard to tell anything goes wrong in a blender script if the user isnt actively expecting errors or knows about the system console

**Comment by ScanMountGoat** [comment]
Another idea might be to show a dialog with details about the error and some guesses about how to fix it. The main benefit being that it looks extra scary so people are less likely to ignore it. https://blender.stackexchange.com/questions/34969/proper-way-to-show-users-error-info-in-the-ui-for-addons

A lot of the errors come from ssbh_data_py when it attempts to calculate tangents. We can't know the exact issue at that point, but it should be doable to at least print the exception message and some suggestions to clean up the geometry. The other lines that may raise exceptions are the save calls like `mesh.save`, `skel.save`, etc.

**Comment by ssbucarlos** [comment]
good idea, that would be alot better for sure

**Comment by ssbucarlos** [comment]
Since blender mesh 'capabilites' (idk if this is the right term) are alot more advanced than what smash (or most other programs) can handle, theres alot of steps the user has to take to 'simplify' the mesh for proper export. Stuff such as applying all modifiers, splitting the mesh by materials, splitting vertices along the UV seams, cleaning degenerate geometry, etc . I plan to eventually take care of these steps automatically in the smush_blender exporter. In doing so, the resulting meshes should be nice and proper, and that should take care of every error i have seen encountered so far in ssbh_data_py. I have yet to see an exception occur in ssbh_data_py that was not due to an issue with the mesh in blender. The menu will still be perfect for unforeseen mesh issues or errors.
