### ISSUE TITLE
Some vanilla models require Mesh->Clean Up->Delete Loose in order to export.

### ISSUE THREAD

**Issue by ssbucarlos** [ssbucarlos/smash-ultimate-blender#29]
This seems to be caused by blender deleting some unneeded or duplicate mesh loops on import, resulting in some loose vertices. The problem can be avoided by automatically doing a Mesh -> Clean Up -> Delete Loose on model import.

**Comment by ScanMountGoat** [comment]
@ssbucarlos Do you remember which in game models are affected by this issue?

**Comment by ssbucarlos** [comment]
Sorry i never got back to this, ill try to find one now, i think it was a bridge of elden mesh

**Comment by ssbucarlos** [comment]
I found meshes 'Left Shape', 'Top Shape', 'RightShape' in `stage/zelda_tower/battle/model/floating_plate_set/model.numshb` that imports with loose edges/vertices, however it seems on export that ssbh_data_py is able to handle it now, so the error is gone.
![image](https://user-images.githubusercontent.com/77519735/233713819-ab7a0a5c-1cff-4b7e-a1b4-8e75d3ff4486.png)
