### ISSUE TITLE
Missing color space setting prevents model import

### ISSUE THREAD

**Issue by newtj** [ssbucarlos/smash-ultimate-blender#46]
While using the [ACES Config](https://github.com/colour-science/OpenColorIO-Configs) in Blender, this removes the standard color spaces in Blender and replaces them with many other color spaces.

Attached is the error given in Blender. 
The main one being "Linear" being removed thus not being found.

Error:
[blender_error.txt](https://github.com/ssbucarlos/smash-ultimate-blender/files/7230557/blender_error.txt)

**Comment by ScanMountGoat** [comment]
I don't think we'll be able to properly support ACES, but I can look into allowing models to import even if the materials can't be properly set up.

**Comment by ScanMountGoat** [comment]
Importing will succeed now, but you'll need to assign a material to each mesh and disable numatb export in the export settings. This should hopefully be simpler in the future.
