### ISSUE TITLE
mesh objects with no parent bone and no bone influences invisible in game after export

### ISSUE THREAD

**Issue by ScanMountGoat** [ssbucarlos/smash-ultimate-blender#52]
This one may be tricky to support. The intuitive thing to do is to assume mesh objects that disable vertex skin weights are parented to a single bone in the skeleton. "Single bind" is term that I haven't seen used outside the Smash modding community and might not be relevant in this case. Newer versions of ssbh_lib just call it `use_vertex_skinning` instead.

ssbh_data and ssbh_data_py disable vertex skinning if there are no bone influences for a mesh object. This is the relevant code from the mesh_data module in Rust.
```rust
use_vertex_skinning: if data.bone_influences.is_empty() {
    0
} else {
    1
}
```

Relevant portions of the unmodified in game version of `stage\sonic_windyhill\normal\model\ring_grass_set\model.numshb` JSON exported by ssbh_lib_json:
```json
"name": "grassShape",
"sub_index": 0,
"parent_bone_name": "",
```

```json
{
    "mesh_object_name": "grassShape",
    "mesh_object_sub_index": 0,
    "flags": {
    "max_influences": 0,
    "unk1": 1
    },
    "buffers": []
},
```

**Comment by ScanMountGoat** [comment]
The issue is that we create vertex groups for every bone on import.
https://github.com/ssbucarlos/smash-ultimate-blender/blob/570855534d446973370168e1fe50f6af696edf78/panels/import_model.py#L408-L411

This means the mesh objects will all have `use_vertex_skinning` set to true on export even if there aren't any influences in the original mesh. For the windy hill mesh, this results in 10 `BoneInfluence` objects with empty weights lists.
https://github.com/ssbucarlos/smash-ultimate-blender/blob/570855534d446973370168e1fe50f6af696edf78/panels/export_model.py#L835

**Comment by ScanMountGoat** [comment]
I think we can just fix this by not creating a bone influence if the weights list is empty. For windy hill, this would create no influences and match the original mesh. I'm not sure if this will always work correctly in game for all fighters and stages or if allowing users to export models with zero vertex weights is always a good idea.

**Comment by ssbucarlos** [comment]
yeah up until now i would have assumed that exporting a model with zero vertex weights is user error. For now what ur suggesting is fine for a hotfix, at least to let stage modders export these stages back into smash without issue. I wanted to look more into how other exporters handle 'single-bind' behavior, i noticed the FBX importer uses 'Bone' parenting type to track the bone in the armature if a mesh is 'single-bound'. I wonder if setting the 'Bone' parenting type, but leaving the field empty, would be a good way to distinguish a mesh imported without weights and an accidental user-made mesh missing weights

**Comment by ssbucarlos** [comment]
ill go ahead and make the hotfix rn

**Comment by ScanMountGoat** [comment]
I put together a file with all effected meshes. This is just the first mesh object from each mesh with all the stage transition models removed.
[no_influences_no_parent_reduced.csv](https://github.com/ssbucarlos/smash-ultimate-blender/files/7766710/no_influences_no_parent_reduced.csv)

**Comment by ssbucarlos** [comment]
oh wow i didnt know there were thousands of affected meshes

**Comment by ScanMountGoat** [comment]
22692 mesh objects in the full version of the csv. Only a small fraction of those are fighters.

**Comment by ScanMountGoat** [comment]
This was fixed at some point, so I'm closing this issue.
