### ISSUE TITLE
Export changes undone by latest commit

### ISSUE THREAD

**Issue by ScanMountGoat** [ssbucarlos/smash-ultimate-blender#54]
This was likely caused by not pulling before making changes. A quick fix is to revert the latest commit and add a new commit that only includes the necessary changed lines for setting bone influences. This gives two new commits to push.

**Comment by ssbucarlos** [comment]
So I noticed i made an initial PR from branch 'windyhillfix' that did not include the latest changes, so i cancelled that PR, deleted branch, and pulled latest changes to 'main' before checking out 'windyhillfix2'. I then copy pasted the hotfix into this new 'windyhillfix2' that i thought had the latest changes. I wonder what happened, im gonna fix it

**Comment by ScanMountGoat** [comment]
One way to do it if you have an outdated branch is to stash any uncommitted changes with `git stash` and then bring the branch up to date. The easiest is to just `git merge main` which leaves merge commit. If you want a cleaner git history, you can google how rebasing works. ~~sometimes I give up and just copy paste the changes somewhere and start over~~

**Comment by ssbucarlos** [comment]
I gave up and copy pasted the file as a new commit 😔 Ill put the intended hotfix back in later tonight,
