### ISSUE TITLE
Replace ssbh_lib_json with ssbh_data_py

### ISSUE THREAD

**Issue by ScanMountGoat** [ssbucarlos/smash-ultimate-blender#55]
This is for tracking what code still needs to be ported. The main benefits are better code readability and cross platform support. Helper bones will likely require JSON for the foreseeable future.

- [x] mesh import
- [x] mesh export 
- [x] skel import
- [x] skel export
- [x] skel export (exo skel) 
- [x] hlpb export (exo skel) 
- [x] matl import 
- [x] matl export 
- [x] #94
- [x] meshex export

**Comment by ssbucarlos** [comment]
ye its alot better to write the code as well when using ssbh_data_py rather than writing json, so i look forward to using ssbh_data_py for the stuff thats currently written to use json.

**Comment by ScanMountGoat** [comment]
It's nice to see this finally completed!
