### ISSUE TITLE
Investigate error messages for improperly configured models

### ISSUE THREAD

**Issue by ScanMountGoat** [ssbucarlos/smash-ultimate-blender#64]
The exceptions generated by Python and ssbh_data_py are precise but not very interpretable or actionable by users. I would probably be confused too if I saw `"zero-size array to reduction operation maximum which has no identity"` when trying to export a numshexb for an empty mesh. ssbh_data_py is designed to use defaults where it makes sense to avoid errors, but there are still a number of unfriendly errors like for calculating tangents.

One approach is to use try/except where appropriate and display a friendly error message first in addition to the Python exception.

- [x] #106
- [x] #92
- [x] #93
- [x] Validate theres only one material per mesh (maybe split by material automatically?)
- [x] Validate that meshes have no degenerate geometry (maybe do this automatically?)
- [x] #117
- [x] #90
- [x] #130
- [x] #104
- [x] #74
- [x] #131
- [x] #110

**Comment by ssbucarlos** [comment]
Idk where to put this check list so ill put it here lol. Let me know if i missed anything. Oh can u edit this comment to add new tasks to this tasklist?

- [ ] Validate that theres any meshes parented to the armature 
- [ ] Validate the model has been triangulated (Maybe do this automatically?)
- [ ] Validate the model has less than 512 bones 
- [ ] Validate theres only one material per mesh (maybe split by material automatically?)
- [ ] Validate that all meshes has no degenerate geometry (maybe do this automatically?)
- [ ] Validate that transforms have been applied (Better behavior might be to calculate world matrix instead)
- [ ] Validate the mesh weights have been cleaned (no Zero-weights)(maybe do this automatically?)
- [ ] Validate the mesh weights have been normalized (Maybe look at the 'deform' weights and do this automatically?)
- [ ] Validate that the mesh has been split along UV seams. There needs to be a one-to-one pairing between mesh vertices and UV coordinates. I don't know how to do this automatically with a 100% success rate using bpy ops.
- [ ] Validate the materials used have the smash_ultimate_shader (maybe attempt to assign a preset material?)
- [ ] Validate the mesh doesnt have too many vertices. I dont know the exact details, but a single mesh having too many vertices causes crashes in game or causes the mesh to be invisible. Perhaps this can be a warning set at 50K vertices.

**Comment by ScanMountGoat** [comment]
People with write access can edit comments. I'm pretty sure it needs to be part of the first comment to show up.

**Comment by ScanMountGoat** [comment]
There may be another buffer size limitation causing issues with too many vertices. The mesh format itself has a theoretical upper limit of 2^32 or 4294967296 vertices. The switch has limited memory, but this is probably a limitation with the shaders/graphics API itself used for their engine.

**Comment by ScanMountGoat** [comment]
The guide here describes many of the common issues before the rework: https://gamebanana.com/tuts/14706

**Comment by ScanMountGoat** [comment]
@ssbucarlos Is it worth trying to validate degenerate geometry on export automatically? Is this something that's easily noticeable from within Blender or SSBH Editor already? I'm not sure how we would define "degenerate" unless you just wanted to run the cleanup and delete loose operations automatically on export. It will be nice to finally finish this issue :)

**Comment by ssbucarlos** [comment]
Ok i can implement running the cleanup and delete loose operations automatically on export

**Comment by ssbucarlos** [comment]
Sorry for the delay :(
its been implemented now.
