### ISSUE TITLE
Missing face when exporting

### ISSUE THREAD

**Issue by cow-killer** [ssbucarlos/smash-ultimate-blender#65]
![2022011101364500-0E7DF678130F4F0FA2C88AE72B47AFDF](https://user-images.githubusercontent.com/12868939/148893459-2d915238-2bda-4d0b-9ca6-021bd3392632.jpg)

Face shows up in blender, not sure why this happens on every export.

**Comment by ssbucarlos** [comment]
Please apply all transforms before exporting. At the moment, transforms need to be applied manually before exported.
![image](https://user-images.githubusercontent.com/77519735/148897352-7895d237-d825-4011-acb2-132783e82d80.png)

**Comment by cow-killer** [comment]
She's still missing her face...I'm guessing all transforms need to be applied to *all* of her expressions? (I only applied to her meshes)

**Comment by ssbucarlos** [comment]
Press 'A' to select everything and then apply transforms. If that still doesnt work, please zip up the blender file and attach here.

**Comment by cow-killer** [comment]
Got it working! Thanks.
