### ISSUE TITLE
MATL export missing blend state unk fields.

### ISSUE THREAD

**Issue by ssbucarlos** [ssbucarlos/smash-ultimate-blender#66]
Without the UNK fields stored, MATL export is missing data. 
- [ ] Update Master Shader in master_shader.py to add the new blend state unk fields
- [ ] Set the fields on matl import
- [ ] Read the fields on matl export

**Comment by ScanMountGoat** [comment]
@ssbucarlos is there some issue that's caused by the missing fields? ssbh_data_py is filling in the missing values with the most common value on save, so nothing is "missing". If something is breaking in game, I can look into updating the API.

**Comment by ssbucarlos** [comment]
Ah that would be perfect for the API to expose the unk types. in "bossstage_final3\normal\model\landscape_st3_both_set", it seems like the unknown 4,6,10 have different values depending on the material. It seems like that after export, theres issues with alpha. I need to do a little bit more testing to 100% confirm that its due to these different unk type values, but i noticed the discrepancies in the MATL and thought that exporting it with 1:1 would be the ideal behavior.

**Comment by ScanMountGoat** [comment]
Is this an import/export without any other edits? I can take a look in an OpenGL debugger with Yuzu or Ryujinx later and see if anything changed.

**Comment by ssbucarlos** [comment]
its a vanilla IO however its replacing the results stage skydome set, so requires ryujinx + arcrop 3.0 beta. Currently running some tests and can confirm that the vanilla IO has alpha issues, however after further testing, the exported NUMATB alone was not enough to cause the issues, and switching between the vanilla numatb and the exported numatb causes no difference. So, i think its safe to say it wasnt the numatb flags after all, im going to keep looking. The only other thing i knew that affected this was the 'depth_flags' of the numshb, however these are identical in the vanilla and exported so im not sure what it could be then.
![2022-01-17_18-26-13](https://user-images.githubusercontent.com/77519735/149852204-dcfad0d6-8305-42ac-843f-dd44221dd595.png)
![2022-01-17_18-28-48](https://user-images.githubusercontent.com/77519735/149852208-b619ab75-6807-429c-bf42-278776b5068b.png)

**Comment by ScanMountGoat** [comment]
Is the sort bias settings in the model.numshb the same for both? If you narrow it down to one file causing the issue, it should be a simple diff of the JSON output with ssbh_lib_json to find what changed.

**Comment by ssbucarlos** [comment]
It seems like the sort bias is the same in both, i cant find a good difference in the numshb. I tried changing the numshexb of the vanilla, also doesnt break it. I imagine it has to be an issue of the numshb, tho im not quite sure what it could be after comparing the two with ssbh_lib_json
[landscape_st3_both_set.zip](https://github.com/ssbucarlos/smash-ultimate-blender/files/7885513/landscape_st3_both_set.zip)
[exported.zip](https://github.com/ssbucarlos/smash-ultimate-blender/files/7885515/exported.zip)

**Comment by ScanMountGoat** [comment]
The only changes I can find are the mesh object order and the bounding information. I would check the order first since it's easier to fix if it turns out to be the issue.

**Comment by ssbucarlos** [comment]
ok ill reorder them for a test and lyk if that fixes it

**Comment by ssbucarlos** [comment]
Update: exporting with order preserved fixes the issue. Gonna push a fix for this soon.
