### ISSUE TITLE
Adjb export (pikachu)

### ISSUE THREAD

**Issue by ScanMountGoat** [ssbucarlos/smash-ultimate-blender#71]
Newer versions of ssbh_data_py support creating model.adjb files from a list of `MeshObjectData`. This seems to only be necessary for models with materials with "RENORMAL" in the name. This signals to the vertex skinning compute shader to recalculate the normals, which can improve the visual quality for animations with a lot of deformation. 

The first issue is that the only way at the moment to reliably generate the appropriate entries in the adjb file is to check the material names. Any mesh object with a material label beginning with "RENORMAL" should be included in the call to `AdjData.from_mesh_objects`. This assumes the materials are assigned and the material label is correctly set. 

Removing "RENORMAL" from all material labels works but leads to distorted normals in game. Mesh objects with "RENORMAL" in the material label without a corresponding adjb entry will have completely broken normals.

The second issue is the lack of documentation for this feature. This could be solved by adding something to https://github.com/ScanMountGoat/Smush-Material-Research to explain why recalculating normals is relevant.

**Comment by ScanMountGoat** [comment]
Affected models:
```
fighter/mariod/model/drmantle/c00/model.numatb, RENORMAL_ShaderfxShader4
fighter/mariod/model/drmantle/c01/model.numatb, RENORMAL_ShaderfxShader4
fighter/mariod/model/drmantle/c02/model.numatb, RENORMAL_ShaderfxShader4
fighter/mariod/model/drmantle/c03/model.numatb, RENORMAL_ShaderfxShader4
fighter/mariod/model/drmantle/c04/model.numatb, RENORMAL_ShaderfxShader4
fighter/mariod/model/drmantle/c05/model.numatb, RENORMAL_ShaderfxShader4
fighter/mariod/model/drmantle/c06/model.numatb, RENORMAL_ShaderfxShader4
fighter/mariod/model/drmantle/c07/model.numatb, RENORMAL_ShaderfxShader4
fighter/pikachu/model/body/c00/model.numatb, RENORMAL_pikachu_facial_03
fighter/pikachu/model/body/c00/model.numatb, RENORMAL_skin_pikachu_001
fighter/pikachu/model/body/c01/model.numatb, RENORMAL_pikachu_facial_03
fighter/pikachu/model/body/c01/model.numatb, RENORMAL_skin_pikachu_001
fighter/pikachu/model/body/c02/model.numatb, RENORMAL_pikachu_facial_03
fighter/pikachu/model/body/c02/model.numatb, RENORMAL_skin_pikachu_001
fighter/pikachu/model/body/c03/model.numatb, RENORMAL_pikachu_facial_03
fighter/pikachu/model/body/c03/model.numatb, RENORMAL_skin_pikachu_001
fighter/pikachu/model/body/c04/model.numatb, RENORMAL_pikachu_facial_03
fighter/pikachu/model/body/c04/model.numatb, RENORMAL_skin_pikachu_001
fighter/pikachu/model/body/c05/model.numatb, RENORMAL_pikachu_facial_03
fighter/pikachu/model/body/c05/model.numatb, RENORMAL_skin_pikachu_001
fighter/pikachu/model/body/c06/model.numatb, RENORMAL_pikachu_facial_03
fighter/pikachu/model/body/c06/model.numatb, RENORMAL_skin_pikachu_001
fighter/pikachu/model/body/c06/model.numatb, RENORMAL_skin_pikachu_002
fighter/pikachu/model/body/c07/model.numatb, RENORMAL_pikachu_facial_03
fighter/pikachu/model/body/c07/model.numatb, RENORMAL_skin_pikachu_002
fighter/pikachu/model/body/c07/model.numatb, RENORMAL_skin_pikachu_003
fighter/reflet/model/chrom/c00/model.numatb, RENORMAL_skin_chrom_001
fighter/reflet/model/chrom/c01/model.numatb, RENORMAL_skin_chrom_001
fighter/reflet/model/chrom/c02/model.numatb, RENORMAL_skin_chrom_001
fighter/reflet/model/chrom/c03/model.numatb, RENORMAL_skin_chrom_001
fighter/reflet/model/chrom/c04/model.numatb, RENORMAL_skin_chrom_001
fighter/reflet/model/chrom/c05/model.numatb, RENORMAL_skin_chrom_001
fighter/reflet/model/chrom/c06/model.numatb, RENORMAL_skin_chrom_001
fighter/reflet/model/chrom/c07/model.numatb, RENORMAL_skin_chrom_001
```

**Comment by ScanMountGoat** [comment]
> The second issue is the lack of documentation for this feature. This could be solved by adding something to https://github.com/ScanMountGoat/Smush-Material-Research to explain why recalculating normals is relevant.

This is part of the material website.
https://scanmountgoat.github.io/Smush-Material-Research/materials/renormal/

**Comment by ssbucarlos** [comment]
i was actually just reading this lol, i had honestly completely forgotten about pikachu and i agree it should be relatively simple, ill go ahead and implement it

**Comment by ssbucarlos** [comment]
Ok its been implemented, i tested in game with pikachu c00 and it seemed to work fine, i didn't notice a difference between the modded/vanilla pikachu c00
