### ISSUE TITLE
latest commit install issue

### ISSUE THREAD

**Issue by ssbucarlos** [ssbucarlos/smash-ultimate-blender#72]
![image](https://user-images.githubusercontent.com/77519735/151067630-a5e4ad4f-733b-45a7-90d6-3c2470cd3c97.png)
a user has reported this issue, i could take a look at it later tho at first glance i think the `operators` is just missing a `.` or `..`

**Comment by ScanMountGoat** [comment]
Good catch. Fixed on latest commit.
