### ISSUE TITLE
Validate presence of smash_ultimate_shader for materials

### ISSUE THREAD

**Issue by ScanMountGoat** [ssbucarlos/smash-ultimate-blender#74]
This seems to be the main issue that users encounter when trying to export files. On the latest commit, this occurs when numatb export is enabled and a material is assigned to a mesh but doesn't contain the smash ultimate shader node group. A related exception happens when the mesh has no materials assigned.

The code needs to handle the following cases or provide a clear error message.
- [x] material assigned with smash ultimate node group
- [x] material assigned but no smash ultimate node group
- [x] material has no node tree
- [x] no material assigned
- [x] the material has multiple materials but no material in the first slot

**Comment by ScanMountGoat** [comment]
If a mesh has a material assigned but doesn't have the appropriate node group, we can still create an entry in the modl to assign the appropriate material label but can't add a corresponding entry to the matl. One way to handle this is to apply a preset material that uses default textures. The generated modl and matl may not have the effect the user intended, so there should be some sort of warning to the user.

If no material is assigned, neither the modl entry nor the matl entry can be created. This condition is harder to handle since not creating the appropriate entries will likely result in the mesh being invisible in game. This is very difficult for users to debug, so it may be best to just abort the export process in this case and explain the issue.

**Comment by ssbucarlos** [comment]
Yeah this error is extremely common, every new user runs into it and the error message doesnt really make it obvious how to fix it. After the anim stuff is complete, this (and other quality-of-life features) are definitely next on the list.
