### ISSUE TITLE
.NUHLPB Import / Export

### ISSUE THREAD

**Issue by ssbucarlos** [ssbucarlos/smash-ultimate-blender#76]
The import of .nuhlpb will help out with ppl creating animations and also ppl re-importing exo skels. 
The incorporation of nuhlpb export into the normal 'export' process will be much less confusing as well.
- [x] import
- [x] export imported models
- [ ] #97

**Comment by ScanMountGoat** [comment]
I did some quick queries and analysis for nuhlpb files that may be useful. Most of the field values don't change, so they probably aren't worth investigating right away. This means `RotateAim` has 4 "interesting" unknown values instead of 22. You can find my comments in the ssbh_lib repo.
https://github.com/ultimate-research/ssbh_lib/blob/master/ssbh_lib/src/formats/hlpb.rs

**Comment by ScanMountGoat** [comment]
The two lists at the end might add additional data to both the rotation and interpolation entries since the counts seem to be related.
[hlpb_counts.csv](https://github.com/ssbucarlos/smash-ultimate-blender/files/8020540/hlpb_counts.csv)

**Comment by ssbucarlos** [comment]
It seems like unk 13-16 is the aim_bone_2 Quaternion Rotation WXYZ in World Space

**Comment by ssbucarlos** [comment]
Genuinely not sure about the rest of the unks. I think that the aim type bone behavior can be approximated in blender by tracking the bone specified by aim_bone_name_1

**Comment by ssbucarlos** [comment]
> The two lists at the end might add additional data to both the rotation and interpolation entries since the counts seem to be related. It could just be sub index for list1 and 1 if the entry is an interpolation entry and 0 otherwise for list2. [hlpb_counts.csv](https://github.com/ssbucarlos/smash-ultimate-blender/files/8020540/hlpb_counts.csv)

oh yeah this is my guess too, and its how i constructed list1 and list2 for the nuhlpb_json for the exo skel maker
