### ISSUE TITLE
Support Blender 3.1+

### ISSUE THREAD

**Issue by ssbucarlos** [ssbucarlos/smash-ultimate-blender#84]
https://wiki.blender.org/wiki/Reference/Release_Notes/3.1/Python_API
Looks like theres some breaking changes due to upgrading to python 3.10
Ill investigate this later and look into making the changes needed, in the meantime, ppl will need to stick to 3.0.
luckily the changes seem to be backwards compatible

**Comment by ScanMountGoat** [comment]
I don't think any of the changes affect us right now. The frame range change might matter once the anim branch is merged. I'll need to update ssbh_data_py to support Python 3.10, which also means dropping support for previous Blender versions that use Python 3.9. If this becomes an issue in the future, we can add multiple releases for supported versions. Staying on a single version and just having people download the addon by downloading the main branch is convenient for now.

**Comment by ScanMountGoat** [comment]
> Wouldn't preliminary support for Blender 3.1+ just be manually typecasting anything that changes Blender scene frame info to an int? That's what was going on [in the old importer](https://gitlab.com/Worldblender/io_scene_numdlb/-/commit/4634585ec629558ebd00bb9f1a5b0b2ae615c8c1). Of course, you'd also have to do other manual typecasts if there are any other spots where the implicit float -> int was used.

Hopefully. The ssbh_data_py binaries need to all be updated to Python 3.10 first for the addon to work on Blender 3.1.
