### ISSUE TITLE
Parent bone not preserved for mesh objects with no bone influences

### ISSUE THREAD

**Issue by ScanMountGoat** [ssbucarlos/smash-ultimate-blender#85]
One possible solution is to convert to regular vertex weights on import and then detect if there is only one influence on export. The downside to this approach is that meshes with no bone influences have slightly different normals when rendered. There may be another Blender feature that would work.
- [x] apply parent transform and set weights on import
- [x] add option to convert to parent bone on export

**Comment by ScanMountGoat** [comment]
Parenting mesh objects with only one influence instead of vertex skinning should be a configurable option. This should default to unchecked since file sizes won't be a concern in most cases. Users modding stages or wanting to optimize file sizes can manually check the option. This also needs to be documented in the wiki.

**Comment by ScanMountGoat** [comment]
The basic process is to apply the parent bone transform on import and set all weights to 1.0 for the parent bone. Exporting is the inverse operation.

**Comment by ssbucarlos** [comment]
Commited + documented on the wiki, sorry for the wait
