### ISSUE TITLE
Missing check for parent in exo skel export

### ISSUE THREAD

**Issue by ScanMountGoat** [ssbucarlos/smash-ultimate-blender#86]
It's not clear as a user why root bones aren't supported or what the exception message means if `smash_bone.parent` is `None`.
https://github.com/ssbucarlos/smash-ultimate-blender/blob/957c8a065ca6ee2d9da4627070c1d4415f042169/panels/exo_skel.py#L407-L408

**Comment by ssbucarlos** [comment]
Yeah this would definitely be a good check to put in. Its not intuitive to a new user why pairing root bones doesn't make sense, leading to alot of preventable error reports
