### ISSUE TITLE
fighter/miifighter/model/b_deacon_m  fails to import.

### ISSUE THREAD

**Issue by ssbucarlos** [ssbucarlos/smash-ultimate-blender#87]
```
in "import_model.py", line 475, in attach_armature_create_vertex_groups
    vertex_group = mesh_obj.vertex_groups[influence.bone_name]
KeyError: 'bpy_prop_collection[key]: key "HandL_eff" not found'
```

(Thanks Devory for finding this!)

**Comment by ScanMountGoat** [comment]
Cross Mod used to have this bug too. There's no "HandL_eff" bone in the skeleton. I'm not sure if anything breaks if we remove the influences that don't refer to valid bones in the skel.
