### ISSUE TITLE
Import error when installing plugin

### ISSUE THREAD

**Issue by cbisbocci** [ssbucarlos/smash-ultimate-blender#89]
I received the following error when installing the plugin, running the most current version of blender as of today. Could it be because I previously installed and uninstalled the carlosSSB animation plugin or already have SSBH.py installed on my 64bit windows PC?
![image](https://user-images.githubusercontent.com/43435942/162412559-429fe0eb-d5c9-4434-9fb7-a9d68425167a.png)

**Comment by ScanMountGoat** [comment]
Are you on Blender 3.1? You'll need to stick to blender 2.93-3.0 for now. Support for 3.1 is planned. We'll be dropping support for older versions, so this change won't be implemented for a while.

**Comment by cbisbocci** [comment]
Thank you for the reply. My bad not reading the documentation properly.
I'll install 3.0!

Cheers

**Comment by ScanMountGoat** [comment]
No worries. It wasn't clear before, so I updated the readme recently.
